sonar.projectKey=moviesapp
sonar.projectName=moviesapp
sonar.sources=frontend,backend,frontend-user

# Ignore unnecessary folders
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/coverage/**